### ISSUE TITLE
PDF seems to be missing a value

### ISSUE THREAD

**Issue by molecule** [96boards/documentation#18]
I'm trying to download and build the source code, following the instructions from here:
https://github.com/96boards/documentation/tree/master/ConsumerEdition/DragonBoard-410c/AdditionalDocs#build-and-installation

The PDF seems to have an error in it. See a screenshot here, from page 8: http://imgur.com/a/ZlyEH

Not sure what is supposed to be there, though...

**Comment by sdrobertw** [comment]
@molecule 

The PDF document you are referring to is a static Qualcomm Developer Network document, I do not have access to the raw document. One of the biggest problems with static documentation is keeping it up to date and/or making small changes without having to push out an entire new version of the doc.

96Boards documentation wants to do away with as much static documentation as possible. This means that over time we will be extracting information from these PDFs to integrate into the github. Anything that does not work, or make sense, will be dropped.

It goes without saying, this transition will take time and effort. It is a work in progress! :)

---

I am not sure if this addresses the issue, but essentially, if something in the document is broken, I can remove the link and ping Qualcomm for review. Since I do not have access to the raw documentation this process is not very cost effective with regard to the amount of time it would take for us to make this small change.

**Comment by molecule** [comment]
I see. That makes sense. As a stop-gap, I can try and figure out what value
should be there, and at least update this thread.

Thanks for all your amazing work and help in this process! Your fast and
thorough responses inspire confidence and build trust in the entire
96boards ecosystem.

I'll keep this issue open for now, and close it once I get more info.
Please don't take the PDF link down, tho! It's still very helpful, and with
this one piece of info will be nearly complete.

**Comment by sdrobertw** [comment]
@molecule 

Can we close this issue?

**Comment by molecule** [comment]
Yeah - I'm not going to be able to find the correct version of the PDF. We
should still work on migrating this documentation from PDF form to your
lovely dynamic system though! If you can push on that, I think it would be
great.

**Comment by sdrobertw** [comment]
@molecule Thanks!

Yes, I will definitely be pushing for this. Thank you very much.
