### ISSUE TITLE
documentation is unclear on "installing" the 410c Camera

### ISSUE THREAD

**Issue by Christopheraburns** [96boards/documentation#292]
The camera guide at: https://github.com/D3Engineering/410c_camera_support/wiki/D3-Camera-Mezzanine-User-Guide  says I can use pre-built releases to flash the Dragonboard (with fastboot).

The link is a redirect and I have to choose from a menu of options, none of which match "camera installation" or anything to that effect. The best option is: Dragonboard Boot Image and it doesn't say anything about the camera image, or how to use FastBoot to install the camera.  

Do I need to flash the 410C board itself - or does this process somehow flash storage on the camera mezzanine board?

**Comment by daniel-thompson** [comment]
I've added a sub-heading to the wiki to help people pick out which of the four links they need to follow.

Beyond that I'm not really sure we can fix this... the problem is broken link on the D3Engineering github so you probably need to report it to them.

For now I think this is the page they should be linking to:
https://www.96boards.org/documentation/consumer/dragonboard410c/installation/linux-fastboot.md.html

**Comment by Mani-Sadhasivam** [comment]
Hi @Christopheraburns,

As stated by @daniel-thompson, please take this issue to D3 Engineering Wiki.
