### ISSUE TITLE
Cannot find the Factory Image zip file

### ISSUE THREAD

**Issue by sylvainpelissier** [96boards/documentation#42]
In the [Installation](ConsumerEdition/HiKey/Installation/README.md) folder, it is mentioned that there is a "Factory Images Method" of installation. However, I am not able to find the "Factory Image zip file" in the [Downloads](/ConsumerEdition/HiKey/Downloads/README.md) repository.

**Comment by sdrobertw** [comment]
@sylvainpelissier : Not all builds offer a factory image download. Currently you will only find a factory image download/installation available under AOSP on the HiKey.

https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Downloads/AOSP.md

This new process is currently in the pipeline. We hope to adapt other images to this model in the near future in order to reduce redundant downloads and installation instruction sets, i.e. and all in one package download.

Please let me know if you have any other questions.

Thanks!

R.W.

**Comment by sylvainpelissier** [comment]
Thank you for your answer.
