### ISSUE TITLE
Andoid install SD on DragonBoard 410c?

### ISSUE THREAD

**Issue by zirill** [96boards/documentation#47]
Help, how to install android?
after installation, only led4

https://github.com/96boards/documentation/wiki/Dragonboard-410c-Installation-Guide-for-Linux-and-Android#installing-image-using-an-sd-card-image

my step
1) download imge: http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/
i used all version, and always the result was one, led4 and no run

2) write SD Card, I used ubuntu(Disk Image Write)
3) set the S6 switch on the DB410c to: 0-1-0-0 {SD Boot switch set to “ON”}
4) run install, after installation extract sd
5) reboot 

led4 and no run (((

ps: Debian is installed immediately without any problems. but I need android

**Comment by sdrobertw** [comment]
@zirill Thank you for a well worded description of your issue. 

Instead of installing the latest release, I would suggest installing the 16.03 release. 
I am fairly sure the 16.06 release is having issues.

Besides this, your process looks fine. The fact that the User LED 4 turns on and then turns off during boot is also a good sign. Once the LED turns off, a few moments later you should see an Android screen pop up on your display (please provide a minute or two).

If you are still experiencing issues with the 16.03 release, please let me know. Please also report back if you are successful in the install.

Thanks! Happy New Year!

**Comment by zirill** [comment]
Thank you.

I installed dragonboard410c_sdcard_install_android-99.zip. Reboot and I waited(after LED off) more than 10 minutes, but nothing happened ((
The monitor has not lighted

Happy New Year!

**Comment by sdrobertw** [comment]
@zirill Happy New Year,

I am sorry you are still having issues. Would you be able to stop by OpenHours this week?

4:00p UTC / 8:00a PST - starting time is at the end of the countdown...

www.96Boards.org/OpenHours

**Comment by zirill** [comment]
Please write the steps you need to do.

**Comment by vchong** [comment]
@zirill Can you try fastboot method [here](https://github.com/Linaro/documentation/blob/master/Reference-Platform/Releases/RPB_16.03/ConsumerEdition/DragonBoard-410c/InstallAOSPRPB-16.03.md)?

**Comment by daniel-thompson** [comment]
I've not run Android in ages but on DB410C there is no bootloader splash screen and the main video stack does not start until the first-boot optimizations are complete. Thus it takes  a *very* long time for an image to appear on the first boot (>2 minutes I think).

If you have waits "a long time" already then the other issue is that, compared to the Debian images, Android is significantly more fussy regarding the display device. IIRC it makes no attempt to probe the monitor to discover what video modes are supports and it outputs full HD (1080p60) by default.

Personally I doubt the problem is causes by a failed installation. We know the installer works because we could use it to install Debian. It is much more likely to be one of the issues above.

**Comment by zirill** [comment]
1) i switch on DragonBoard™ 410c must be set to ‘0-0-0-0’. All switches should be in “off” position
2) I connected to the TV(FHD) and it worked

PS: monitor(FHD) for some reason did not want to

**Comment by zirill** [comment]
how to get access to "adb"?

**Comment by vchong** [comment]
`sudo apt-get install android-tools-adb`

**Comment by zirill** [comment]
ADB write that without access to the device

**Comment by vchong** [comment]
Try sudo with the adb commands, or refer to Section 3.2 of https://developer.qualcomm.com/qfile/28828/lm80-p0436-2_sw-build-and-install_gd_linux_android.pdf.

You can only use the microusb or (regular) usb one at a time so if you have an active adb connection on the board, any mouse or keyboard connected to it will not work. See http://www.96boards.org/forums/topic/android-on-96boards-faq/#post-14462 for details. Sorry :(.

**Comment by sdrobertw** [comment]
@zirill I would like to close this issue. 

Are you still having problems when flashing Android to your 96Boards?

**Comment by Ankitaasharmaa** [comment]
I need help! currently i am doing work from  windows10 and downloaded Debian image file from https://www.96boards.org/documentation/consumer/dragonboard410c/downloads/debian.md.html and trying to boot it from SD card but i am not able get a dialogue box for installing operating system in Dragonboard410c. I had properly wrote the image file into SD card(8GB) through win32diskimager. While flashing through SD card on board ,i am getting a command saying linaro username and password .What should i do next .Please help me fast ,if anyone knows the solution.

**Comment by ric96** [comment]
@Ankitaasharmaa this issue section is for issues related to only the documentation section of our website. Any issues related to the software running on any of our boards or issues related to the hardware itself need to be asked on our forum: https://discuss.96boards.org
