### ISSUE TITLE
Instructions for booting Ubuntu on Rock960 via SD deficient 

### ISSUE THREAD

**Issue by seanrmurphy** [96boards/documentation#541]
The ubuntu image linked to assumes that the root-fs is mounted on /dev/mmcblk1p5 but in a standard Rock960 system, the SD card mounts on /dev/mmcblk0p5. The result is that when booting from SD, the ubuntu boot process does not find the root-fs and fails.

It is not difficult to change - just change the boot params on the 4th partition to point to the correct device.

This should be noted.

Also, it's not clear what credentials are baked into the ubuntu image linked to from here.

**Comment by Mani-Sadhasivam** [comment]
@seanrmurphy Not sure why you hit this error! In my board I can successfully boot from SD card. As you said, SD was assigned to `mmcblk0` and eMMC was `mmcblk1` still if nothing on SD card, it boots from eMMC otherwise it boots from SD card.

If you need to debug this isssue further, I would encourage you to move the thread to [forum](https://discuss.96boards.org/c/products/rock960).

**Comment by Mani-Sadhasivam** [comment]
Closing as the reporter agreed to move the topic to forum!

**Comment by seanrmurphy** [comment]
Issue has already been raised on forum - https://discuss.96boards.org/t/sd-card-boot-not-working/5145/7
