### ISSUE TITLE
lunch hikey970-userdebug does not work

### ISSUE THREAD

**Issue by Linuxuser4** [96boards/documentation#554]
I am trying to follow instructions on page https://github.com/96boards/documentation/blob/master/consumer/hikey/hikey970/build/aosp.md for building system images to be run on hikey970 board. I find that lunch command does not show options for hikey970-userdebug. All I get is for hikey960-userdebug and hikey-userdebug. Can I get correct options for hikey970?

**Comment by Linuxuser4** [comment]
Also, I build the Hikey970 kernel based on https://github.com/96boards/documentation/blob/master/consumer/hikey/hikey970/build/linux-kernel.md , (with system images built for Hikey960, since options to build Hikey970 is absent). I tried flashing the kernel (change jumper 3 to ON; fastboot flash boot boot.img; change jumper3 to OFF). The board does not boot up. Looks like kernel crashed. Any pointers or ideas to correct documentation?

**Comment by ric96** [comment]
@Linuxuser4 its possible that the lunch menu doesn't show the hikey970-userdebug option, but the ```lunch hikey970-userdebug``` command still works, I just tested it.

Boot images built for 960 will NOT work for 970.

If any further issues arise, you can post it on our forums at https://discuss.96boards.org/ and tag me, we usually use this issue section for issues related specifically to the documentation itself(broken links, typos etc.). This issue topic seems a bit grey, but I believe its an issue on your end instead of the doc itself.
