### ISSUE TITLE
SD Card Installation Guide Missing

### ISSUE THREAD

**Issue by Jeeppler** [96boards/documentation#63]
Hello,

for some reason there is no SD Card installation guide anymore. If am on the following page: https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Downloads/Debian.md and click on the 'Continue to Installation page' I end up on this page: https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Installation/README.md . However, this page does only provide information on how to install Debian with the `fastboot` method. 8-9 months ago you had a guide for the SD Card installation. Where did you put the guide? Why is the SD Card installation guide missing?

**Comment by vchong** [comment]
Try https://github.com/Linaro/documentation/blob/master/Reference-Platform/Releases/RPB_16.06/ConsumerEdition/HiKey/InstallDebianRPB.md#sd-card-method?

**Comment by sdrobertw** [comment]
@Jeeppler 

I will be bringing back or linking the SD Card method soon to the main HiKey doc landing page. Until then, I will leave this issue open. Thank you for the catch!

**Comment by ubitux** [comment]
I tried to `dd` the sdcard image from http://builds.96boards.org/releases/reference-platform/debian/hikey/16.06/ as suggested by the Linaro link shared, but it doesn't seem to be enough. The sdcard is not bootable, and there is nothing on the serial interfaces (nor HDMI fwiw) after the grub menu.

I'm looking forward information wrt SD card, because it's extremely painful to work with the emmc.

**Comment by sdrobertw** [comment]
[UPDATE]

We are still trying to get the HiKey SD Card image and instructions working and updated. We hope to have this ready by mid Sept 2017.

Thanks!

**Comment by bbusacker** [comment]
@sdrobertw Are we on track for mid September?  SD card support and docs?

**Comment by sdrobertw** [comment]
@bbusacker Still working on this issue. Unfortunately the SD method of installation has gone stale and support for it is also lacking. I am trying to muster the resources to do as many test in order to get a new set of instructions on onto the repo... 

@Mani-Sadhasivam @ric96 : please help in pursuing a working SD Card image for the HiKey6220 with working instructions. We will want to add this to the HiKey6220 docs pages under the installation instructions sections (focus on host machine "Linux" only for now).

**Comment by Mani-Sadhasivam** [comment]
Hi @Jeeppler @bbusacker @sdrobertw,

We now have the [instructions](https://github.com/96boards/documentation/blob/master/consumer/hikey/installation/linux-sd-boot.md) for booting from SD card for Hikey 

Thanks for your patience!
