### ISSUE TITLE
rock: install: Troubleshooting guide is not a great way to handle permissions problems

### ISSUE THREAD

**Issue by ClarenceYk** [96boards/documentation#748]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/rock/installation/linux-mac-rkdeveloptool.md.html

Command `lsusb` shows the following message:
```Shell
Bus 003 Device 006: ID 2207:0011
```

But when I try `rkdeveloptool` with argument `ld` to show USB devices, it comes:
```Shell
not found any devices!
```

Then I checked the source code of `rkdeveloptool`, I found this:
```C
typedef enum{
	RKNONE_DEVICE = 0,
	RK27_DEVICE = 0x10,
	RKCAYMAN_DEVICE,
	RK28_DEVICE = 0x20,
	RK281X_DEVICE,
	RKPANDA_DEVICE,
	RKNANO_DEVICE = 0x30,
	RKSMART_DEVICE,
	RKCROWN_DEVICE = 0x40,
	RK29_DEVICE = 0x50,
	RK292X_DEVICE,
	RK30_DEVICE = 0x60,
	RK30B_DEVICE,
	RK31_DEVICE = 0x70,
	RK32_DEVICE = 0x80
} ENUM_RKDEVICE_TYPE;
```

Seems that `rkdeveloptool` doesn't support RK3399 yet.

**Comment by daniel-thompson** [comment]
Hi @Mani-Sadhasivam

Clarence (correctly) took this to the forum and whilst I'm not yet sure if we have fixed the problem the docs here are definitely suboptimal. Currently there are separate Linux/Mac sections but, for most users, the Linux section will not actually work if the troubleshooting advise appended to the bottom of the page is found and followed. Since the user would have to scroll down several screens following the broken instruction I suspect many will never see the troubleshooting section (at least until after a good deal of frustration... specially give the error from rkdeveloptool doesn't mention permissions). It would be much better to integrate advise on the correct permissions settings into the main body of the instructions.
